version: '3.8'

services:
  # 1. MQTT Broker
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - "1885:1883"
    volumes:
      - ./infra/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./infra/mosquitto/data:/mosquitto/data
      - ./infra/mosquitto/log:/mosquitto/log

  # 2. Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 3. Kafka Brokers (3-Node)
  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-1
    depends_on: [zookeeper]
    ports: ["29092:29092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      # JVM 힙 메모리를 256MB로 제한
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"

  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-2
    depends_on: [zookeeper]
    ports: ["29093:29093"]
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      # JVM 힙 메모리를 256MB로 제한
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"

  kafka-3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-3
    depends_on: [zookeeper]
    ports: ["29094:29094"]
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,EXTERNAL://localhost:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      # JVM 힙 메모리를 256MB로 제한
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
  # 4. OTA Agent (가상 차량 1,000대 시뮬레이터)
  ota-agent:
    build:
      context: .
      dockerfile: cmd/agent/Dockerfile
    container_name: ota-agent
    depends_on:
      - mqtt-broker
    environment:
      - BROKER_URL=tcp://mqtt-broker:1883
    volumes:
    # 호스트의 data 폴더를 컨테이너의 /root/data 폴더로 연결
    # (실행 스테이지의 WORKDIR가 /root/ 이므로 상대 경로를 맞춤)
     - ./data:/root/data
    restart: always

  # 5. OTA Server (관제 서버)
  ota-server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    container_name: ota-server
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - mqtt-broker
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
