apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ota-agent
spec:
  serviceName: "ota-agent"
  replicas: 1000
  podManagementPolicy: Parallel

  selector:
    matchLabels:
      app: ota-agent

  template:
    metadata:
      labels:
        app: ota-agent

    spec:
      # [변경] Tolerations를 삭제했습니다. 
      # 이제 마스터 노드의 Taint를 통과하지 못하므로 워커에만 배포됩니다.

      containers:
      - name: ota-agent
        image: ota-agent:v4
        imagePullPolicy: IfNotPresent
        env:
        - name: BROKER_URL
          value: "tcp://192.168.56.1:1883"
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 5m
            memory: 8Mi
          limits:
            cpu: 20m
            memory: 16Mi
        volumeMounts:
        - name: inventory-volume
          mountPath: /etc/ota
        - name: agent-data
          mountPath: /var/lib/ota-agent

      volumes:
      - name: inventory-volume
        configMap:
          name: ota-inventory
      - name: agent-data
        emptyDir:
          sizeLimit: 50Mi

      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: ota-agent
