-- HANA DB 테이블 및 인덱스 설계

-- 1. 차량 마스터 정보
CREATE COLUMN TABLE VEHICLES (
       VEHICLE_ID VARCHAR(50) PRIMARY KEY,
       MODEL VARCHAR(30),
       STATUS VARCHAR(20) -- READY, UPDATING, ERROR
);

-- 2. 차량별 ECU 현황 (버전 정수형 분리)
CREATE COLUMN TABLE ECUS (
       ID INTEGER PRIMARY KEY,
       VEHICLE_ID VARCHAR(50),
       ECU_TYPE VARCHAR(20), -- BMS, BCM, VCU 등
       MAJOR_V INTEGER,
       MINOR_V INTEGER,
       PATCH_V INTEGER,
       FOREIGN KEY (VEHICLE_ID) REFERENCES VEHICLES(VEHICLE_ID)
);

-- 조회 성능을 위한 인덱스
-- 차량 ID로 ECU를 검색하는 쿼리가 많으므로 필수
CREATE INDEX  IDX_ECU_VEHICLE ON ECUs(VEHIICLEPID);

-- 3. OTA 업데이트 패키지
CREATE COLUMN TABLE UPDATE_PACKAGES (
       PACKAGE_ID VARCHAR(50) PRIMARY KEY,
       TARGET_ECU_TYPE VARCHAR(20),
       TARGET_MAJOR_V INTEGER,
       TARGET_MINOR_V INTEGER,
       TARGET_PATCH_V INTEGER
);

-- 4. 의존성 규칙
CREATE COLUMN TABLE DEPENDENCY_RULES (
       RULE_ID INTEGER PRIMARY KEY,
       PACKAGE_ID VARCHAR(50),
       REQUIRED_ECU_TYPE VARCHAR(20),
       MIN_MAJOR_V INTEGER,
       MIN_MINOR_V INTEGER,
       MIN_PATCH_V INTEGER,
       FOREIGN KEY (PACKAGE_ID) REFERENCES UPDATE_PACKAGES(PACKAGE_ID)
);

-- 패키지별 규칙 조회 성능 향상을 위한 인덱스
CREATE INDEX IDX_RULE_PACKAGE ON DEPENDENCY_RULES(PACKAGE_ID);