/* =====================================================================
   OTA DEPLOYMENT & DEPENDENCY VALIDATOR SCHEMA (LEVEL 1)
   Description: 차량 인벤토리 관리, 의존성 검증 및 배터리 진단 시스템
   Database: SAP HANA (Column-based Storage)
   ===================================================================== */

-- [0. 시스템 설정]
-- MySQL Native Password 설정 (필요 시 유지)
-- ALTER USER 'root'@'localhost' IDENTIFIED VIA mysql_native_password USING PASSWORD('1234');
-- FLUSH PRIVILEGES;

/* ---------------------------------------------------------------------
   PART 1: 개체 초기화 (Cleanup)
   의존성 관계를 고려하여 뷰(View)부터 테이블 순으로 삭제합니다.
   --------------------------------------------------------------------- */
DROP VIEW v_ota_eligibility_check;
DROP TABLE "Update_History";
DROP TABLE "Dependency_Rules";
DROP TABLE "Deployment_Campaigns";
DROP TABLE "Update_Packages";
DROP TABLE "Vehicle_ECU_Inventory";
DROP TABLE "Vehicles";

/* ---------------------------------------------------------------------
   PART 2: 핵심 스키마 생성 (DDL)
   --------------------------------------------------------------------- */

-- 1. 차량 마스터 정보 (Vehicles)
-- 차량의 고유 식별 정보와 지역 정보를 관리합니다.
CREATE COLUMN TABLE "Vehicles" (
    "VEHICLE_ID" BIGINT PRIMARY KEY,
    "VIN" VARCHAR(17) UNIQUE NOT NULL,      -- 차대번호 (ISO 3779)
    "MODEL_CODE" VARCHAR(10) NOT NULL,      -- 차종 코드 (예: GN7, NQ5)
    "REGION" VARCHAR(10)                    -- 판매 지역 (KOR, USA, EUR)
);

-- 2. 차량 제어기 인벤토리 (Vehicle_ECU_Inventory)
-- 차량이 보고한 실시간 SW/HW 상태 및 배터리 진단 데이터를 통합 관리합니다.
CREATE COLUMN TABLE "Vehicle_ECU_Inventory" (
    "VEHICLE_ID" BIGINT,
    "ECU_TYPE" VARCHAR(20),                 -- 제어기 도메인 (BMS, VCU, ADAS 등)
    "HW_VERSION" VARCHAR(20),               -- 물리적 하드웨어 버전
    "SW_MAJOR_V" INTEGER,
    "SW_MINOR_V" INTEGER,
    "SW_PATCH_V" INTEGER,
    "BATTERY_SOH" DOUBLE,                   -- 배터리 건강 상태 (0.0~1.0)
    "BATTERY_VOLTAGE" DOUBLE,               -- 업데이트 시점 전압 (V)
    "LAST_REPORTED_AT" TIMESTAMP,
    PRIMARY KEY ("VEHICLE_ID", "ECU_TYPE")
);

-- 3. OTA 배포 패키지 (Update_Packages)
-- 배포될 펌웨어 메타데이터와 무결성 검증을 위한 해시를 관리합니다.
CREATE COLUMN TABLE "Update_Packages" (
    "PACKAGE_ID" VARCHAR(50) PRIMARY KEY,
    "TARGET_ECU_TYPE" VARCHAR(20),
    "TARGET_HW_VERSION" VARCHAR(20),
    "SW_MAJOR_V" INTEGER,
    "SW_MINOR_V" INTEGER,
    "SW_PATCH_V" INTEGER,
    "EXPECTED_HASH" VARCHAR(64),            -- ISO 21434 기반 SHA-256 검증 해시
    "FILE_URL" VARCHAR(255)                 -- 패키지 다운로드 경로
);

-- 4. 업데이트 의존성 규칙 (Dependency_Rules)
-- SDV 환경에서 제어기 간 정합성 보장을 위한 선행 버전 규칙을 정의합니다.
CREATE COLUMN TABLE "Dependency_Rules" (
    "RULE_ID" INTEGER PRIMARY KEY,
    "PACKAGE_ID" VARCHAR(50),               -- 대상 패키지
    "REQUIRED_ECU_TYPE" VARCHAR(20),        -- 선행 확인 제어기
    "MIN_SW_MAJOR_V" INTEGER,               -- 필수 요구 버전(Major)
    "MIN_SW_MINOR_V" INTEGER,
    "MIN_SW_PATCH_V" INTEGER
);

-- 5. 배포 캠페인 (Deployment_Campaigns)
-- 특정 차종 및 기간을 지정하여 배포를 수행하는 비즈니스 단위입니다.
CREATE COLUMN TABLE "Deployment_Campaigns" (
    "CAMPAIGN_ID" BIGINT PRIMARY KEY,
    "PACKAGE_ID" VARCHAR(50),
    "TARGET_MODEL_CODE" VARCHAR(10),
    "STATUS" VARCHAR(20),                   -- ACTIVE, PAUSED, FINISHED
    "START_DATE" TIMESTAMP,
    "END_DATE" TIMESTAMP
);

-- 6. 업데이트 이력 및 상세 에러 로그 (Update_History)
-- 장애 분석(Root Cause Analysis) 및 통계 분석을 위한 이력 테이블입니다.
CREATE COLUMN TABLE "Update_History" (
    "HISTORY_ID" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "VIN" VARCHAR(17),
    "CAMPAIGN_ID" BIGINT,
    "CURRENT_STATUS" VARCHAR(20),           -- DOWNLOADING, VERIFYING, SUCCESS, FAILED
    "ERROR_CODE" VARCHAR(10),               -- ERR_001(Hash), ERR_004(Voltage), ERR_005(Dependency)
    "UPDATE_START_TIME" TIMESTAMP,
    "UPDATE_END_TIME" TIMESTAMP
);

/* ---------------------------------------------------------------------
   PART 3: 비즈니스 로직 뷰 (Views)
   --------------------------------------------------------------------- */

-- 지능형 배포 가용성 검증 뷰 (v_ota_eligibility_check)
-- SAP HANA의 실시간 연산을 활용하여 차량별 업데이트 적격 여부를 즉시 판단합니다.
CREATE VIEW v_ota_eligibility_check AS
SELECT
    v.VIN,
    v.MODEL_CODE,
    c.CAMPAIGN_ID,
    p.PACKAGE_ID,
    p.TARGET_ECU_TYPE,
    CASE
        -- 1단계: 배터리 전압 검증 (Safety Gate - 11.5V 기준)
        WHEN i.BATTERY_VOLTAGE < 11.5 THEN 'ERR_004_LOW_VOLTAGE'

        -- 2단계: 하드웨어 호환성 검증
        WHEN i.HW_VERSION IS NULL THEN 'ECU_NOT_FOUND'
        WHEN i.HW_VERSION != p.TARGET_HW_VERSION THEN 'INCOMPATIBLE_HW'

        -- 3단계: 의존성 소프트웨어 버전 검증 (타 제어기 선행 조건 체크)
        WHEN EXISTS (
            SELECT 1
            FROM "Dependency_Rules" dr
                     INNER JOIN "Vehicle_ECU_Inventory" e
                                ON e.VEHICLE_ID = v.VEHICLE_ID
                                    AND e.ECU_TYPE = dr.REQUIRED_ECU_TYPE
            WHERE dr.PACKAGE_ID = p.PACKAGE_ID
              AND (
                e.SW_MAJOR_V < dr.MIN_SW_MAJOR_V
                    OR (e.SW_MAJOR_V = dr.MIN_SW_MAJOR_V AND e.SW_MINOR_V < dr.MIN_SW_MINOR_V)
                    OR (e.SW_MAJOR_V = dr.MIN_SW_MAJOR_V AND e.SW_MINOR_V = dr.MIN_SW_MINOR_V AND e.SW_PATCH_V < dr.MIN_SW_PATCH_V)
                )
        ) THEN 'ERR_005_DEPENDENCY_MISMATCH'

        -- 4단계: 최신 버전 여부 확인 (중복 업데이트 방지)
        WHEN (i.SW_MAJOR_V > p.SW_MAJOR_V)
            OR (i.SW_MAJOR_V = p.SW_MAJOR_V AND i.SW_MINOR_V > p.SW_MINOR_V)
            OR (i.SW_MAJOR_V = p.SW_MAJOR_V AND i.SW_MINOR_V = p.SW_MINOR_V AND i.SW_PATCH_V >= p.SW_PATCH_V)
            THEN 'ALREADY_UP_TO_DATE'

        ELSE 'READY'
        END AS ELIGIBILITY_STATUS
FROM "Vehicles" v
         INNER JOIN "Deployment_Campaigns" c ON v.MODEL_CODE = c.TARGET_MODEL_CODE
         INNER JOIN "Update_Packages" p ON c.PACKAGE_ID = p.PACKAGE_ID
         LEFT JOIN "Vehicle_ECU_Inventory" i ON v.VEHICLE_ID = i.VEHICLE_ID AND i.ECU_TYPE = p.TARGET_ECU_TYPE
WHERE c.STATUS = 'ACTIVE'
  AND CURRENT_TIMESTAMP BETWEEN c.START_DATE AND c.END_DATE;