name: OTA DevOps CI/CD

on:
  push:
    branches: [ main, chore, "feature/**" ]
  pull_request:
    branches: [ main ]
    types: [labeled, opened, synchronize, reopened] # PR 관련 이벤트 구체화

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Go Build Check (Agent)
        run: |
          cd cmd/agent
          go build -v -o /dev/null ./main.go

      - name: Go Build Check (Server)
        run: |
          cd cmd/server
          go build -v -o /dev/null ./main.go

  automerge:
    needs: test-and-build
    runs-on: ubuntu-latest
    # PR 이벤트이거나, 특정 라벨이 붙었을 때 실행되도록 설정 가능
    if: github.event_name == 'pull_request'

    # 머지 권한 부여
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          # 머지 실패 시 에러를 내지 않고 조용히 넘어가게 하려면 아래 옵션 추가
          # MERGE_RETRIES: "3"
          # MERGE_RETRY_SLEEP: "10000"